Add unique index to ZippedMoabVersions.
sul-dlss/preservation_catalog pull request #1957
Opened 2022-10-18 14:43 UTC by justinlittman

closes #1831

## Why was this change made? 🤔
Safety.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md).⚡

Verified that no existing zipped moab versions violate this constraint in all environments.

2022-10-18 14:50 UTC, edsu approved these changes

2022-10-18 14:51 UTC, edsu requested changes
Do you have any idea why the tests are failing here?

2022-10-18 16:06 UTC, ndushay approved these changes

2022-10-18 16:13 UTC, edsu approved these changes

2022-10-18 16:22 UTC, merged

2022-10-20 21:47 UTC, ndushay commented
Does this need to be deployed, with a full backup, separately from dep updates?

2022-10-21 12:12 UTC, justinlittman commented
I don't think that is necessitated by this change. The worst that could happen is creating the index fails.

2022-10-24 15:28 UTC, jmartin-sul commented
just in case the migration takes a couple minutes to run, deploying this change now, before dep updates go out (but not doing the snapshot first, since this has an exceedingly low risk of introducing bad data):

- [x] tag de76a0a20cfe6a931dacdefb17e856ff4390565d (includes daily CV/C2A audits for evening load)
  - https://github.com/sul-dlss/preservation_catalog/compare/rel-2022-10-17...zmv-unique-per-druid-endpoint-version
- [x] turn off google books
- [x] stop pres robots
- [x] stop pres cat workers
- [x] query pres cat DB to make sure no contraint violating rows (`ZippedMoabVersion.group(:preserved_object_id, :zip_endpoint_id, :version).having('count(id) > 1').pluck(:preserved_object_id, :zip_endpoint_id, :version)`)
  - returns `[]` as expected
- [ ] deploy tag
- [ ] start pres cat workers
- [ ] start pres robots
- [ ] turn on google books

2022-10-24 15:49 UTC, jmartin-sul commented
done, took about 40 seconds for the migration to run:
```
00:32 deploy:migrating
      01 bundle exec rake db:migrate
      01 == 20221018143200 AddUniqueZippedMoabVersions: migrating ======================
      01 -- add_index(:zipped_moab_versions, [:preserved_object_id, :zip_endpoint_id, :version], {:unique=>true, :name=>"ind…
      01    -> 26.5345s
      01 == 20221018143200 AddUniqueZippedMoabVersions: migrated (26.5347s) ============
      01
    ✔ 01 pres@preservation-catalog-prod-02.stanford.edu 39.175s
```