remove primary_moab_location endpoint
sul-dlss/preservation_catalog pull request #1998
Opened 2022-10-28 22:38 UTC by ndushay

## Why was this change made? 🤔

there is no need for "primary moab" concept.

Part of #1977

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md).⚡

2022-10-28 22:39 UTC, ndushay commented
tagging @justinlittman - I'm still looking for more code for primary moab, but this is a nice small PR.

2022-10-28 23:12 UTC, mjgiarlo requested changes
Should this PR include the dashboard stuff? Guessing not.

2022-10-29 00:07 UTC, ndushay commented
> Should this PR include the dashboard stuff? Guessing not.

whoops!   How did that get in here?  Removed now.

2022-10-31 11:33 UTC, justinlittman approved these changes

2022-10-31 15:45 UTC, mjgiarlo approved these changes

2022-10-31 15:45 UTC, merged