add new rubocops and fixes for them
sul-dlss/preservation_catalog pull request #2243
Opened 2023-06-19 22:32 UTC by ndushay

## Why was this change made? 🤔

OCD

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, **_run [integration test preassembly_image_accessioning_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/preassembly_image_accessioning_spec.rb) against stage as it tests preservation_**, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `DeliveryDispatcherJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md).⚡

2023-06-20 11:07 UTC, justinlittman approved these changes
Please disable `RSpec/IndexedLet` in .rubocop.yml. We clearly don't intend to enforce it and putting it inline is just noise.

2023-06-20 11:08 UTC, justinlittman requested changes
Please disable `RSpec/IndexedLet` in .rubocop.yml. We clearly don't intend to enforce it and putting it inline is just noise.

2023-07-05 17:20 UTC, ndushay commented
@justinlittman I turned off RSpec/IndexedLet rules so this is ready for another look.

2023-07-05 17:58 UTC, justinlittman approved these changes

2023-07-05 17:59 UTC, merged